# -*- mode: ruby -*-
# vi: set ft=ruby :

# Prefix for Network
SUBNET="192.168.1."
#Environment Domain
DOMAIN="Cryolab.local"
#Server configs
servers=[
  {
    :hostname => "Greybeard." + DOMAIN,
    :ip => SUBNET + "50",
    :ip_int => "1",
    :ram => 2000,
    :cpu => 2,
    :box => "centos/7",
    :hdd => 50000,
    :disk => "./greybeard.vdi"
  },
  {
    :hostname => "Greybeard2." + DOMAIN,
    :ip => SUBNET + "51",
    :ip_int => "1",
    :ram => 2000,
    :cpu => 2,
    :box => "centos/7",
    :hdd => 50000,
    :disk => "./greybeard2.vdi"
  }
]

Vagrant.configure("2") do |config|
 # config.vm.box = "centos/7"

  servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
                vb.customize ["modifyhd", machine[:disk], "--resize", machine[:hdd]]
            end
        end
    end
  end